/* Allegro datafile object indexes, produced by grabber v3.12 */
/* Datafile: e:\compi\revista2\sliders2.dat */
/* Date: Mon May 17 18:00:42 1999 */
/* Do not hand edit! */

#define FOTO_ATARI_DEMOS_1               0        /* BMP  */
#define FOTO_ATARI_DEMOS_2               1        /* BMP  */
#define FOTO_ATARI_DISKMAG_1             2        /* BMP  */
#define FOTO_ATARI_DISKMAG_2             3        /* BMP  */
#define FOTO_ATARI_DISKMAG_3             4        /* BMP  */
#define FOTO_ATARI_EMULADOR_1            5        /* BMP  */
#define FOTO_ATARI_EMULADOR_2            6        /* BMP  */
#define FOTO_ATARI_HARDWARE_1            7        /* BMP  */
#define FOTO_ATARI_HARDWARE_2            8        /* BMP  */
#define FOTO_ATARI_HARDWARE_3            9        /* BMP  */
#define FOTO_ATARI_HARDWARE_4            10       /* BMP  */
#define FOTO_ATARI_HARDWARE_5            11       /* BMP  */
#define FOTO_ATARI_HARDWARE_6            12       /* BMP  */
#define FOTO_ATARI_JOYSTICK_1            13       /* BMP  */
#define FOTO_BEOS_DIBUJO_1               14       /* BMP  */
#define FOTO_BEOS_DIBUJO_2               15       /* BMP  */
#define FOTO_BEOS_DIBUJO_3               16       /* BMP  */
#define FOTO_BEOS_DOSBOX_1               17       /* BMP  */
#define FOTO_BEOS_DRIVERS_1              18       /* BMP  */
#define FOTO_CPC_DISCO_1                 19       /* BMP  */
#define FOTO_CPC_FUENTE_1                20       /* BMP  */
#define FOTO_CPC_SCART_1                 21       /* BMP  */
#define FOTO_CPC_SCART_2                 22       /* BMP  */
#define FOTO_DAMPDOS_1                   23       /* BMP  */
#define FOTO_DEMOS64_1                   24       /* BMP  */
#define FOTO_DEMOS64_2                   25       /* BMP  */
#define FOTO_DEMOS64_3                   26       /* BMP  */
#define FOTO_DEMOSCPC_1                  27       /* BMP  */
#define FOTO_DEMOSCPC_2                  28       /* BMP  */
#define FOTO_DEMOSCPC_3                  29       /* BMP  */
#define FOTO_DEMOSCPC_4                  30       /* BMP  */
#define FOTO_DEMOSCPC_5                  31       /* BMP  */
#define FOTO_DEMOSCPC_6                  32       /* BMP  */
#define FOTO_DISKMAG64_1                 33       /* BMP  */
#define FOTO_DISKMAG64_2                 34       /* BMP  */
#define FOTO_DISKMAG64_3                 35       /* BMP  */
#define FOTO_DISKMAG64_4                 36       /* BMP  */
#define FOTO_DISKMAG64_5                 37       /* BMP  */
#define FOTO_DISKMAG64_6                 38       /* BMP  */
#define FOTO_DISKMAGSCPC_1               39       /* BMP  */
#define FOTO_DISKMAGSCPC_2               40       /* BMP  */
#define FOTO_DISKMAGSCPC_3               41       /* BMP  */
#define FOTO_DISKMAGSCPC_4               42       /* BMP  */
#define FOTO_DISKMAGZ80_1                43       /* BMP  */
#define FOTO_DISKMAGZ80_2                44       /* BMP  */
#define FOTO_DISKMAGZ80_3                45       /* BMP  */
#define FOTO_DIVXBEOS_1                  46       /* BMP  */
#define FOTO_EMULADOR64_1                47       /* BMP  */
#define FOTO_EMULADOR64_2                48       /* BMP  */
#define FOTO_EMULADORCPC_1               49       /* BMP  */
#define FOTO_EMULADORCPC_2               50       /* BMP  */
#define FOTO_EMULADORCPC_3               51       /* BMP  */
#define FOTO_EMULADORZ80_1               52       /* BMP  */
#define FOTO_EMULADORZ80_2               53       /* BMP  */
#define FOTO_EMULADORZ80_3               54       /* BMP  */
#define FOTO_EMULADORZ80_4               55       /* BMP  */
#define FOTO_EMULADORZ80_5               56       /* BMP  */
#define FOTO_EMULADORZ80_6               57       /* BMP  */
#define FOTO_EMULADORZ80_7               58       /* BMP  */
#define FOTO_ENTREVISTABEOS_1            59       /* BMP  */
#define FOTO_EXILIUM_1                   60       /* BMP  */
#define FOTO_LEVEL64_1                   61       /* BMP  */
#define FOTO_LEVEL64_10                  62       /* BMP  */
#define FOTO_LEVEL64_11                  63       /* BMP  */
#define FOTO_LEVEL64_12                  64       /* BMP  */
#define FOTO_LEVEL64_13                  65       /* BMP  */
#define FOTO_LEVEL64_14                  66       /* BMP  */
#define FOTO_LEVEL64_2                   67       /* BMP  */
#define FOTO_LEVEL64_3                   68       /* BMP  */
#define FOTO_LEVEL64_4                   69       /* BMP  */
#define FOTO_LEVEL64_5                   70       /* BMP  */
#define FOTO_LEVEL64_6                   71       /* BMP  */
#define FOTO_LEVEL64_7                   72       /* BMP  */
#define FOTO_LEVEL64_8                   73       /* BMP  */
#define FOTO_LEVEL64_9                   74       /* BMP  */
#define FOTO_MENUET_1                    75       /* BMP  */
#define FOTO_MENUET_2                    76       /* BMP  */
#define FOTO_MENUET_3                    77       /* BMP  */
#define FOTO_OXYGENCPC_1                 78       /* BMP  */
#define FOTO_OXYGENCPC_2                 79       /* BMP  */
#define FOTO_OXYGENCPC_3                 80       /* BMP  */
#define FOTO_PIRATA_1                    81       /* BMP  */
#define FOTO_QUBEDOS_1                   82       /* BMP  */
#define FOTO_QUBEDOS_2                   83       /* BMP  */
#define FOTO_QVDOS_1                     84       /* BMP  */
#define FOTO_RADIO_INTEK_1               85       /* BMP  */
#define FOTO_RED64_1                     86       /* BMP  */
#define FOTO_RED64_2                     87       /* BMP  */
#define FOTO_REVISTA_1                   88       /* BMP  */
#define FOTO_REVISTA_2                   89       /* BMP  */
#define FOTO_REVISTA_3                   90       /* BMP  */
#define FOTO_REVISTA_4                   91       /* BMP  */
#define FOTO_REVISTA_5                   92       /* BMP  */
#define FOTO_REVISTA_6                   93       /* BMP  */
#define FOTO_REVISTA_7                   94       /* BMP  */
#define FOTO_SCENE_ASSEMBLY_1            95       /* BMP  */
#define FOTO_SCENE_ASSEMBLY_2            96       /* BMP  */
#define FOTO_SCENE_ASSEMBLY_3            97       /* BMP  */
#define FOTO_SCENE_ASSEMBLY_4            98       /* BMP  */
#define FOTO_SCENE_ASSEMBLY_5            99       /* BMP  */
#define FOTO_SCENE_ASSEMBLY_6            100      /* BMP  */
#define FOTO_SCENE_BCNX_1                101      /* BMP  */
#define FOTO_SCENE_BCNX_2                102      /* BMP  */
#define FOTO_SCENE_BCNX_3                103      /* BMP  */
#define FOTO_SCENE_BCNX_4                104      /* BMP  */
#define FOTO_SCENE_BCNX_5                105      /* BMP  */
#define FOTO_SCENE_EUSKALX_1             106      /* BMP  */
#define FOTO_SCENE_EUSKALX_2             107      /* BMP  */
#define FOTO_SCENE_EUSKALX_3             108      /* BMP  */
#define FOTO_SCENE_EUSKALX_4             109      /* BMP  */
#define FOTO_SCENE_EUSKALX_5             110      /* BMP  */
#define FOTO_SCENE_EUSKALX_6             111      /* BMP  */
#define FOTO_SCENE_EUSKALX_7             112      /* BMP  */
#define FOTO_SCENE_EUSKALX_8             113      /* BMP  */
#define FOTO_SCENE_EUSKALX_9             114      /* BMP  */
#define FOTO_SPRINTERZ80_1               115      /* BMP  */
#define FOTO_SPRINTERZ80_2               116      /* BMP  */
#define FOTO_SPRINTERZ80_3               117      /* BMP  */
#define FOTO_SPRINTERZ80_4               118      /* BMP  */
#define FOTO_SPRINTERZ80_5               119      /* BMP  */
#define FOTO_SPRINTERZ80_6               120      /* BMP  */
#define FOTO_Z80_CROSS_1                 121      /* BMP  */
#define PALETA_ATARI_DEMOS_1             122      /* PAL  */
#define PALETA_ATARI_DEMOS_2             123      /* PAL  */
#define PALETA_ATARI_DISKMAG_1           124      /* PAL  */
#define PALETA_ATARI_DISKMAG_2           125      /* PAL  */
#define PALETA_ATARI_DISKMAG_3           126      /* PAL  */
#define PALETA_ATARI_EMULADOR_1          127      /* PAL  */
#define PALETA_ATARI_EMULADOR_2          128      /* PAL  */
#define PALETA_ATARI_HARDWARE_1          129      /* PAL  */
#define PALETA_ATARI_HARDWARE_2          130      /* PAL  */
#define PALETA_ATARI_HARDWARE_3          131      /* PAL  */
#define PALETA_ATARI_HARDWARE_4          132      /* PAL  */
#define PALETA_ATARI_HARDWARE_5          133      /* PAL  */
#define PALETA_ATARI_HARDWARE_6          134      /* PAL  */
#define PALETA_ATARI_JOYSTICK_1          135      /* PAL  */
#define PALETA_BEOS_DIBUJO_1             136      /* PAL  */
#define PALETA_BEOS_DIBUJO_2             137      /* PAL  */
#define PALETA_BEOS_DIBUJO_3             138      /* PAL  */
#define PALETA_BEOS_DOSBOX_1             139      /* PAL  */
#define PALETA_BEOS_DRIVERS_1            140      /* PAL  */
#define PALETA_CPC_DISCO_1               141      /* PAL  */
#define PALETA_CPC_FUENTE_1              142      /* PAL  */
#define PALETA_CPC_SCART_1               143      /* PAL  */
#define PALETA_CPC_SCART_2               144      /* PAL  */
#define PALETA_DAMPDOS_1                 145      /* PAL  */
#define PALETA_DEMOS64_1                 146      /* PAL  */
#define PALETA_DEMOS64_2                 147      /* PAL  */
#define PALETA_DEMOS64_3                 148      /* PAL  */
#define PALETA_DEMOSCPC_1                149      /* PAL  */
#define PALETA_DEMOSCPC_2                150      /* PAL  */
#define PALETA_DEMOSCPC_3                151      /* PAL  */
#define PALETA_DEMOSCPC_4                152      /* PAL  */
#define PALETA_DEMOSCPC_5                153      /* PAL  */
#define PALETA_DEMOSCPC_6                154      /* PAL  */
#define PALETA_DISKMAG64_1               155      /* PAL  */
#define PALETA_DISKMAG64_2               156      /* PAL  */
#define PALETA_DISKMAG64_3               157      /* PAL  */
#define PALETA_DISKMAG64_4               158      /* PAL  */
#define PALETA_DISKMAG64_5               159      /* PAL  */
#define PALETA_DISKMAG64_6               160      /* PAL  */
#define PALETA_DISKMAGSCPC_1             161      /* PAL  */
#define PALETA_DISKMAGSCPC_2             162      /* PAL  */
#define PALETA_DISKMAGSCPC_3             163      /* PAL  */
#define PALETA_DISKMAGSCPC_4             164      /* PAL  */
#define PALETA_DISKMAGZ80_1              165      /* PAL  */
#define PALETA_DISKMAGZ80_2              166      /* PAL  */
#define PALETA_DISKMAGZ80_3              167      /* PAL  */
#define PALETA_DIVXBEOS_1                168      /* PAL  */
#define PALETA_EMULADOR64_1              169      /* PAL  */
#define PALETA_EMULADOR64_2              170      /* PAL  */
#define PALETA_EMULADORCPC_1             171      /* PAL  */
#define PALETA_EMULADORCPC_2             172      /* PAL  */
#define PALETA_EMULADORCPC_3             173      /* PAL  */
#define PALETA_EMULADORZ80_1             174      /* PAL  */
#define PALETA_EMULADORZ80_2             175      /* PAL  */
#define PALETA_EMULADORZ80_3             176      /* PAL  */
#define PALETA_EMULADORZ80_4             177      /* PAL  */
#define PALETA_EMULADORZ80_5             178      /* PAL  */
#define PALETA_EMULADORZ80_6             179      /* PAL  */
#define PALETA_EMULADORZ80_7             180      /* PAL  */
#define PALETA_ENTREVISTABEOS_1          181      /* PAL  */
#define PALETA_EXILIUM_1                 182      /* PAL  */
#define PALETA_LEVEL64_1                 183      /* PAL  */
#define PALETA_LEVEL64_10                184      /* PAL  */
#define PALETA_LEVEL64_11                185      /* PAL  */
#define PALETA_LEVEL64_12                186      /* PAL  */
#define PALETA_LEVEL64_13                187      /* PAL  */
#define PALETA_LEVEL64_14                188      /* PAL  */
#define PALETA_LEVEL64_2                 189      /* PAL  */
#define PALETA_LEVEL64_3                 190      /* PAL  */
#define PALETA_LEVEL64_4                 191      /* PAL  */
#define PALETA_LEVEL64_5                 192      /* PAL  */
#define PALETA_LEVEL64_6                 193      /* PAL  */
#define PALETA_LEVEL64_7                 194      /* PAL  */
#define PALETA_LEVEL64_8                 195      /* PAL  */
#define PALETA_LEVEL64_9                 196      /* PAL  */
#define PALETA_MENUET_1                  197      /* PAL  */
#define PALETA_MENUET_2                  198      /* PAL  */
#define PALETA_MENUET_3                  199      /* PAL  */
#define PALETA_OXYGENCPC_1               200      /* PAL  */
#define PALETA_OXYGENCPC_2               201      /* PAL  */
#define PALETA_OXYGENCPC_3               202      /* PAL  */
#define PALETA_PIRATA_1                  203      /* PAL  */
#define PALETA_QUBEDOS_1                 204      /* PAL  */
#define PALETA_QUBEDOS_2                 205      /* PAL  */
#define PALETA_QVDOS_1                   206      /* PAL  */
#define PALETA_RADIO_INTEK_1             207      /* PAL  */
#define PALETA_RED64_1                   208      /* PAL  */
#define PALETA_RED64_2                   209      /* PAL  */
#define PALETA_REVISTA_1                 210      /* PAL  */
#define PALETA_REVISTA_2                 211      /* PAL  */
#define PALETA_REVISTA_3                 212      /* PAL  */
#define PALETA_REVISTA_4                 213      /* PAL  */
#define PALETA_REVISTA_5                 214      /* PAL  */
#define PALETA_REVISTA_6                 215      /* PAL  */
#define PALETA_REVISTA_7                 216      /* PAL  */
#define PALETA_SCENE_ASSEMBLY_1          217      /* PAL  */
#define PALETA_SCENE_ASSEMBLY_2          218      /* PAL  */
#define PALETA_SCENE_ASSEMBLY_3          219      /* PAL  */
#define PALETA_SCENE_ASSEMBLY_4          220      /* PAL  */
#define PALETA_SCENE_ASSEMBLY_5          221      /* PAL  */
#define PALETA_SCENE_ASSEMBLY_6          222      /* PAL  */
#define PALETA_SCENE_BCNX_1              223      /* PAL  */
#define PALETA_SCENE_BCNX_2              224      /* PAL  */
#define PALETA_SCENE_BCNX_3              225      /* PAL  */
#define PALETA_SCENE_BCNX_4              226      /* PAL  */
#define PALETA_SCENE_BCNX_5              227      /* PAL  */
#define PALETA_SCENE_EUSKALX_1           228      /* PAL  */
#define PALETA_SCENE_EUSKALX_2           229      /* PAL  */
#define PALETA_SCENE_EUSKALX_3           230      /* PAL  */
#define PALETA_SCENE_EUSKALX_4           231      /* PAL  */
#define PALETA_SCENE_EUSKALX_5           232      /* PAL  */
#define PALETA_SCENE_EUSKALX_6           233      /* PAL  */
#define PALETA_SCENE_EUSKALX_7           234      /* PAL  */
#define PALETA_SCENE_EUSKALX_8           235      /* PAL  */
#define PALETA_SCENE_EUSKALX_9           236      /* PAL  */
#define PALETA_SPRINTERZ80_1             237      /* PAL  */
#define PALETA_SPRINTERZ80_2             238      /* PAL  */
#define PALETA_SPRINTERZ80_3             239      /* PAL  */
#define PALETA_SPRINTERZ80_4             240      /* PAL  */
#define PALETA_SPRINTERZ80_5             241      /* PAL  */
#define PALETA_SPRINTERZ80_6             242      /* PAL  */
#define PALETA_Z80_CROSS_1               243      /* PAL  */
#define TEXTO_ATARI_DEMOS                244      /* DATA */
#define TEXTO_ATARI_DISKMAG              245      /* DATA */
#define TEXTO_ATARI_EMULADOR             246      /* DATA */
#define TEXTO_ATARI_HARDWARE             247      /* DATA */
#define TEXTO_ATARI_JOYSTICK             248      /* DATA */
#define TEXTO_BEOS_DIBUJO                249      /* DATA */
#define TEXTO_BEOS_DIVX                  250      /* DATA */
#define TEXTO_BEOS_DOSBOX                251      /* DATA */
#define TEXTO_BEOS_DRIVERS               252      /* DATA */
#define TEXTO_BEOS_ENTREVISTA            253      /* DATA */
#define TEXTO_BITSHORT                   254      /* DATA */
#define TEXTO_C64_CROSS                  255      /* DATA */
#define TEXTO_C64_DEMOS                  256      /* DATA */
#define TEXTO_C64_DISKMAG                257      /* DATA */
#define TEXTO_C64_EMULADOR               258      /* DATA */
#define TEXTO_C64_LEVEL64                259      /* DATA */
#define TEXTO_C64_RED                    260      /* DATA */
#define TEXTO_CPC_CINTAS                 261      /* DATA */
#define TEXTO_CPC_CROSS                  262      /* DATA */
#define TEXTO_CPC_DEMOS                  263      /* DATA */
#define TEXTO_CPC_DISCO                  264      /* DATA */
#define TEXTO_CPC_DISKMAGS               265      /* DATA */
#define TEXTO_CPC_EMULADOR               266      /* DATA */
#define TEXTO_CPC_FUENTE                 267      /* DATA */
#define TEXTO_CPC_OXYGEN                 268      /* DATA */
#define TEXTO_CPC_SCART                  269      /* DATA */
#define TEXTO_DARKBASIC                  270      /* DATA */
#define TEXTO_DOS_COVOX                  271      /* DATA */
#define TEXTO_DOS_DAMP                   272      /* DATA */
#define TEXTO_DOS_QUBE                   273      /* DATA */
#define TEXTO_DOS_QV                     274      /* DATA */
#define TEXTO_EXILIUM                    275      /* DATA */
#define TEXTO_FORO                       276      /* DATA */
#define TEXTO_GBA                        277      /* DATA */
#define TEXTO_LENGUAJE_C                 278      /* DATA */
#define TEXTO_MENUET                     279      /* DATA */
#define TEXTO_PIRATA                     280      /* DATA */
#define TEXTO_RADIO_ENTREVISTA           281      /* DATA */
#define TEXTO_RADIO_INTEK                282      /* DATA */
#define TEXTO_RADIO_MORSE                283      /* DATA */
#define TEXTO_REVISTA                    284      /* DATA */
#define TEXTO_SCENE_ASSEMBLY             285      /* DATA */
#define TEXTO_SCENE_BCNX                 286      /* DATA */
#define TEXTO_SCENE_DEBATE               287      /* DATA */
#define TEXTO_SCENE_EUSKALX              288      /* DATA */
#define TEXTO_SDL                        289      /* DATA */
#define TEXTO_Z80_CROSS                  290      /* DATA */
#define TEXTO_Z80_DISKMAG                291      /* DATA */
#define TEXTO_Z80_EMULADOR               292      /* DATA */
#define TEXTO_Z80_SPRINTER               293      /* DATA */

